2018/03/16 09:13:28 [error] [application] exception 'Exception' with message 'test' in /sample-php7/yii1/testdrive/protected/commands/SampleCommand.php:7
Stack trace:
#0 [internal function]: SampleCommand->actionIndex()
#1 /sample-php7/yii1/testdrive/vendor/yiisoft/yii/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(SampleCommand), Array)
#2 /sample-php7/yii1/testdrive/vendor/yiisoft/yii/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#3 /sample-php7/yii1/testdrive/vendor/yiisoft/yii/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#4 /sample-php7/yii1/testdrive/vendor/yiisoft/yii/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#5 /sample-php7/yii1/testdrive/vendor/yiisoft/yii/framework/yiic.php(33): CApplication->run()
#6 /sample-php7/yii1/testdrive/protected/yiic.php(7): require_once('/sample-php7/yi...')
#7 /sample-php7/yii1/testdrive/protected/yiic(4): require_once('/sample-php7/yi...')
#8 {main}
